spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workcv
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create  # ho?c validate/protect ? prod
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

